---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transform
spec:
  selector:
    matchLabels:
      app: transform
  template:
    metadata:
      labels:
        app: transform
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "transform"
        vault.hashicorp.com/agent-cache-enable: "true"
        vault.hashicorp.com/agent-cache-use-auto-auth-token: "true"  
    
    spec:
      serviceAccountName: transform
      containers:
      - name: transform
        env:
        - name: KAFKA_GROUP
          value: 'app-a-group'
        - name: INGRESS_TOPIC
          value: 'app-a-ingress'
        - name: EGRESS_TOPIC
          value: 'app-a-egress-dev'
        - name: SECRETS_PATH
          value: 'kv/data/confluent-cloud'
        - name: CONFIGS_PATH
          value: 'kv/data/app-a/config'
        - name: VAULT_ADDR
          value: 'http://localhost:8200'
        - name: VAULT_TOKEN
          value: ''
        - name: LOGLEVEL
          value: 'DEBUG'
        image: moayadi/vault-confluentcloud-demo:transform-latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---

kind: Service
apiVersion: v1
metadata:
  name:  transform
spec:
  selector:
    app:  transform
  type:  ClusterIP
  ports:
  - name:  tcp
    port:  8080
    targetPort:  8080

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name:  transform